name: Custom Env Variables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: write value to $GITHUB_ENV file
        run: echo "VAR_1=value set from first step" >> "$GITHUB_ENV"

      - name: dispaly value of VAR_1
        run: echo "Value of VAR_1 is $VAR_1"

      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
