name: Build code and call reusable deploy workflow TEMPLATE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build-job:
    runs-on: windows-latest
      
    steps:

      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'

      - name: Build code
        run: dotnet build --configuration Release

      - name: Publish code
        run: dotnet publish -c Release --property:PublishDir="${{env.DOTNET_ROOT}}\myapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          # Artifact name
          name: .net-app
          path: ${{env.DOTNET_ROOT}}\myapp

  call-reusable-deployment-workflow-job:
    needs: build-job

    uses: morrisseycode-ps/shared-workflows/.github/workflows/reusable-deploy-shared-repo.yml@main
    with:
      package-name: .net-app
      app-name: appsvc1
      deployment-slot: development
    secrets: 
      azure-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
